// <auto-generated />
namespace AMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SemesterModelAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SemesterModelAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201308300950232_SemesterModelAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
